from app.models import db, Post, User, environment

def seed_likes():
    demo = User.query.get(1)
    jamie = User.query.get(2)
    jordan = User.query.get(3)
    nick = User.query.get(4)
    maria = User.query.get(5)
    shaina = User.query.get(6)
    brennen = User.query.get(7)
    andrew = User.query.get(8)
    sara = User.query.get(9)
    alex = User.query.get(10)
    katharine = User.query.get(11)
    marty = User.query.get(12)
    leslie = User.query.get(13)
    matt = User.query.get(14)
    gray = User.query.get(15)
    mike = User.query.get(16)
    jacob = User.query.get(17)
    tyler = User.query.get(18)

    post1 = Post.query.get(1)
    post2 = Post.query.get(2)
    post3 = Post.query.get(3)
    post4 = Post.query.get(4)
    post5 = Post.query.get(5)
    post6 = Post.query.get(6)
    post7 = Post.query.get(7)
    post8 = Post.query.get(8)
    post9 = Post.query.get(9)
    post10 = Post.query.get(10)
    post11 = Post.query.get(11)
    post12 = Post.query.get(12)
    post13 = Post.query.get(13)
    post14 = Post.query.get(14)
    post15 = Post.query.get(15)
    post16 = Post.query.get(16)
    post17 = Post.query.get(17)
    post18 = Post.query.get(18)

    demo.user_likes.extend([post3, post7, post10, post13, post14])
    jamie.user_likes.extend([post2, post3, post4, post10, post11, post12, post13, post14])
    jordan.user_likes.extend([post2, post3, post4, post6, post11, post12, post13, post14])
    nick.user_likes.extend([post2, post3, post5, post6, post8, post11, post14])
    maria.user_likes.extend([post4, post7, post11, post12, post13, post14])
    shaina.user_likes.extend([post3, post6, post9, post10, post15, post16, post17, post18])
    brennen.user_likes.extend([post2, post3, post4, post5, post6])
    andrew.user_likes.extend([post7, post4, post8, post9, post10, post15, post16, post17, post18, post11, post13, post14])
    sara.user_likes.extend([post1, post5, post6])
    alex.user_likes.extend([post1, post2, post3, post5, post6, post9])
    katharine.user_likes.extend([post1, post2, post4])
    marty.user_likes.extend([post2, post3, post5, post6])
    leslie.user_likes.extend([post7, post11])
    matt.user_likes.extend([post7, post8, post9, post10, post15, post17, post18, post11])
    gray.user_likes.extend([post10, post15, post16, post17, post18, post11])
    mike.user_likes.extend([post7, post8])
    jacob.user_likes.extend([post1, post3, post4, post5, post6, post9])
    tyler.user_likes.extend([post7, post3, post10, post4, post15, post16, post17, post18, post11, post1, post9])

    db.session.commit()

def undo_likes():
    if environment == "production":
        db.session.execute(f"TRUNCATE table likes RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM likes")
        db.session.commit()
