"""add read boolean to message

Revision ID: 1ae4ae6a365c
Revises: ea09f7bf5a3d
Create Date: 2023-01-06 17:20:44.875610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae4ae6a365c'
down_revision = 'ea09f7bf5a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'read')
    # ### end Alembic commands ###
